//
//  HomeViewControllerSpec.swift
//  GitRepos
//
//  Created by Gilson Gil on 23/03/19.
//  Copyright (c) 2019 Gilson Gil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import GitRepos

import Quick
import Nimble

final class HomeViewControllerSpec: QuickSpec {
  override func spec() {
    let sut = HomeViewController()
    let window = UIWindow()
    window.rootViewController = sut
    window.makeKeyAndVisible()

    describe("given an home view controller") {
      context("when successfully loaded") {
        it("should fetch a list of 20 repos") {
          expect(sut.homeView?.tableView.numberOfRows(inSection: 0))
            .toEventuallyNot(equal(0), timeout: 5, pollInterval: 1, description: nil)
        }
      }

      context("when fetching a second page") {
        it("should fetch another 20 repos and sum to have 40 repos") {
          sut.fetchNextPage()
          expect(sut.homeView?.tableView.numberOfRows(inSection: 0))
            .toEventually(equal(40), timeout: 5, pollInterval: 1, description: nil)
        }
      }

      context("when pulled to refresh") {
        it("should clear list of repos and fetch a list of 20 repos") {
          sut.didPullRefresh(at: HomeView())
          expect(sut.homeView?.tableView.numberOfRows(inSection: 0))
            .toEventually(equal(20), timeout: 5, pollInterval: 1, description: nil)
        }
      }
    }
  }
}
