default_platform(:ios)

platform :ios do
  desc "Run slather to create test coverage report"
  lane :coverage do
    slather(
      scheme: "GitRepos",
      workspace: "GitRepos.xcworkspace",
      proj: "GitRepos.xcodeproj"
    )
  end
end
