//
//  HomeWorker.swift
//  GitRepos
//
//  Created by Gilson Gil on 23/03/19.
//  Copyright (c) 2019 Gilson Gil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class HomeWorker {
  private var currentTask: URLSessionTask?

  func fetch(page: Int, completion: @escaping (() throws -> [Repository]) -> Void) {
    if currentTask != nil {
      currentTask?.cancel()
      currentTask = nil
    }
    currentTask = API.getRepositories(page: page, completion: completion)
  }
}
